services:
  - type: web
    name: mmo-tg
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: BASE_URL
        fromService:
          type: web
          name: mmo-tg
          property: host
    healthCheckPath: /
    autoDeploy: true